"""made changes

Revision ID: 1780543297
Revises: 1780532526
Create Date: 2026-06-03 21:21:37.369697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1780543297'
down_revision: Union[str, Sequence[str], None] = '1780532526'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('item_name_key'), 'item', type_='unique')
    op.add_column('item_type', sa.Column('code_name', sa.String(length=64), nullable=True))
    op.add_column('item_type', sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('item_type_name_key'), 'item_type', type_='unique')
    op.drop_constraint(op.f('item_type_plural_name_key'), 'item_type', type_='unique')
    op.drop_constraint(op.f('item_type_singular_name_key'), 'item_type', type_='unique')
    op.create_unique_constraint(None, 'item_type', ['code_name'])
    op.drop_column('item_type', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_type', type_='unique')
    op.create_unique_constraint(op.f('item_type_singular_name_key'), 'item_type', ['singular_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('item_type_plural_name_key'), 'item_type', ['plural_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('item_type_name_key'), 'item_type', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('item_type', 'fields')
    op.drop_column('item_type', 'code_name')
    op.create_unique_constraint(op.f('item_name_key'), 'item', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
