"""made changes

Revision ID: 1780877129
Revises: 1780543297
Create Date: 2026-06-07 18:05:30.463462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780877129'
down_revision: Union[str, Sequence[str], None] = '1780543297'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('account_history', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('board_comment', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('board_post', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('item', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('item_type', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('log_entry', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('log_event', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('role', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('role', 'updated')
    op.drop_column('log_event', 'updated')
    op.drop_column('log_entry', 'updated')
    op.drop_column('item_type', 'updated')
    op.drop_column('item', 'updated')
    op.drop_column('board_post', 'updated')
    op.drop_column('board_comment', 'updated')
    op.drop_column('account_history', 'updated')
    op.drop_column('account', 'updated')
    # ### end Alembic commands ###
