"""made changes

Revision ID: 1780530209
Revises: 1780530010
Create Date: 2026-06-03 17:43:30.159483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780530209'
down_revision: Union[str, Sequence[str], None] = '1780530010'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type', sa.Column('singular_name', sa.String(length=64), nullable=True))
    op.add_column('item_type', sa.Column('plural_name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'item_type', ['plural_name'])
    op.create_unique_constraint(None, 'item_type', ['singular_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_type', type_='unique')
    op.drop_constraint(None, 'item_type', type_='unique')
    op.drop_column('item_type', 'plural_name')
    op.drop_column('item_type', 'singular_name')
    # ### end Alembic commands ###
