"""made changes

Revision ID: 1780531389
Revises: 1780530209
Create Date: 2026-06-03 18:03:09.831416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780531389'
down_revision: Union[str, Sequence[str], None] = '1780530209'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('item_type_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('item_type_id_fkey'), 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'item_type', ['item_type_id'], ['id'])
    op.drop_column('item', 'type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_type_id_fkey'), 'item', 'item_type', ['type_id'], ['id'])
    op.drop_column('item', 'item_type_id')
    # ### end Alembic commands ###
