"""made changes

Revision ID: 1780967487
Revises: 1780877129
Create Date: 2026-06-08 19:11:27.894944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780967487'
down_revision: Union[str, Sequence[str], None] = '1780877129'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    op.add_column('item_type', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'item_type', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_type', type_='foreignkey')
    op.drop_column('item_type', 'user_id')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'user_id')
    # ### end Alembic commands ###
